# ============================================================
# SmartHarvest Platform — Development Environment Overrides
# ============================================================
# Namespace: dev
# Only override what differs from values.yaml
# CI updates image tags here:
#   yq -i ".services.<service-name>.image.tag = \"<tag>\"" values/values-dev.yaml
# ============================================================

global:
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
services:
  user-service:
    replicaCount: 1
    image:
      repository: preethi236/user-service
      tag: "dev-553ad7cc458555b19919ee8dd6abe067345fa555"
  crop-advisory-service:
    replicaCount: 1
    image:
      repository: preethi236/crop-advisory-service
      tag: "dev-abe77cf3d257da1a46dc93de8b444ca6aecb2974"
  marketplace-service:
    replicaCount: 1
    image:
      repository: preethi236/marketplace-service
      tag: "dev-7c1ea25c85f6466c3e07911b6d44ea791ad4bf44"
  frontend-service:
    replicaCount: 1
    image:
      repository: preethi236/frontend-service
      tag: "dev-1d88d8731e8a24117f7dc4b373638e7ea30802bf"
