# ============================================================
# SmartHarvest Platform — Development Environment Overrides
# ============================================================
# Namespace: dev
# Only override what differs from values.yaml
# CI updates image tags here:
#   yq -i ".services.<service-name>.image.tag = \"<tag>\"" values/values-dev.yaml
# ============================================================

global:
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
services:
  user-service:
    replicaCount: 1
    image:
      repository: preethi236/user-service
      tag: "dev-e35f817763aa6c90b933b99dfde0608e1818a42e"
  crop-advisory-service:
    replicaCount: 1
    image:
      repository: preethi236/crop-advisory-service
      tag: "dev-a7a9dbe73b8d0e233ef09a2f3b611a5842ad19c7"
  marketplace-service:
    replicaCount: 1
    image:
      repository: preethi236/marketplace-service
      tag: "dev-7c1ea25c85f6466c3e07911b6d44ea791ad4bf44"
  frontend-service:
    replicaCount: 1
    image:
      repository: preethi236/frontend-service
      tag: "dev-a117212b5da82bc8cb0fa2bc663897a29c9eaf22"
