# ============================================================
# SmartHarvest Platform — Development Environment Overrides
# ============================================================
# Namespace: dev
# Only override what differs from values.yaml
# CI updates image tags here:
#   yq -i ".services.<service-name>.image.tag = \"<tag>\"" values/values-dev.yaml
# ============================================================

global:
  imagePullPolicy: Always
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"
services:
  user-service:
    replicaCount: 1
    image:
      repository: preethi236/user-service
      tag: "dev-898ea111f3461ef45654ede222f7de331c911b85"
  crop-advisory-service:
    replicaCount: 1
    image:
      repository: preethi236/crop-advisory-service
      tag: "dev-a7a9dbe73b8d0e233ef09a2f3b611a5842ad19c7"
  marketplace-service:
    replicaCount: 1
    image:
      repository: preethi236/marketplace-service
      tag: "dev-ceab26a61313bee04023608dd0d3aa797dc7933c"
  frontend-service:
    replicaCount: 1
    image:
      repository: preethi236/frontend-service
      tag: "dev-a117212b5da82bc8cb0fa2bc663897a29c9eaf22"
