apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketplace-service-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: smartharvest
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Smart-Harvest/SmartHarvest-HelmCharts.git
    targetRevision: HEAD
    path: microservices/marketplace-service
    helm:
      valueFiles:
        - ../../values/values.yaml
        - ../../values/values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
