apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: smartharvest-gateway
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.infrastructure.gateway.className }}
  listeners:
    {{- range .Values.infrastructure.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      allowedRoutes:
        namespaces:
          from: Same
    {{- end }}
