apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.userService.port | quote }}
  JWT_ALGORITHM: {{ .Values.jwt.algorithm | quote }}
  JWT_EXPIRY_MINUTES: {{ .Values.jwt.expiryMinutes | quote }}
