apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.user }}"
  DATABASE_URL_SYNC: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.user }}"
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
