apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-service-config
  labels:
    {{- include "marketplace-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.marketplaceService.port | quote }}
  JWT_ALGORITHM: {{ .Values.jwt.algorithm | quote }}
