apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  labels:
    {{- include "marketplace-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.marketplaceService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "marketplace-service.selectorLabels" . | nindent 4 }}
