apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: crop-advisory-service-secret
  namespace: dev
spec:
  encryptedData:
    DATABASE_URL: AgCV5AE7AuFIhK1ZhsPmBR6V/tS1S99UxdLEhS87D7cRTSHdp7clbmP8zS+ddnjsDEesGzeqFp/ay/Gm8AxyZnjvW1JZt23yS/A9mmrycyjg05l0Scv/lrx9K579d0wU8V6crPuzCb2z8+8RWs4WpH/v5QVEKr207UjIbLQgxm7m1YlJHKro+2hv2fo6VMCTIPodQ0Nd/YwgoJylgD6t2hJHxgkpYSRpYEsK2Zyg+xwsSY1vk5RPUWHeMg1X/7F45w2YABvWpsy2pTG9LgMbf45RVpVaoAX2ApZdgIj3OaZNXP2md5wcoQbADK2vnYZdJVJfPFFwRvop1SwvN4tb2R1YiscgfHQmP3qnkjRmPMeHoaCwv1amI1QWH8AowiKu9m2m7jsgeBFXMaSXrwQJGOzkQC7zha+6mdA0r6HJ0Ek+yqHAlU1iHnqHjKrwrz7wEG6vXZkexp1x9K/i9e3/XzdwLCVpsrnZKrndj91OzuU4IVXxaFuG7BvGnvCI2fvJJ9d+G28troaS99yX1y4s7kWgO+7AwEgIW1ELwY0Frz8MCpx5fcibrmvkqXZfYU0r4uxwy0ZUYr9sRtAE5WMxVTYjP0TiydAsLZFMwxXEy1HnN/feMPTNBypFBzskiUx3Nw59oxgGEbzjNqFUHBaUavZZaPVlcM+1oPq9YPB8JcNC5W9dhER2Jm0Rg5X7K+brvIGQrCqRmPT3eRyhbYR+JIgWAHMVKHNW/7PSvGWDVYb+17WwiIFZqsW25bI7uNp9Y6WslmR/vsVPHfOkqonS3isp5VwzLw==
    DATABASE_URL_SYNC: AgBlkBv89xYL31Ff11MUB8KObAhHMbmi2siQJAfN+el7eQEijuo/EJp+YpQ+UYiBePgJ5Ib9fVRFJyJi6cdcV4I/R7bEImtH+64TqSQLanfoDag8521IEHPkkwfMszRD2cygM782VGTPG1Ibilxn237Szxu1R+rfG0FqMZ1DUlqg9Mqsw7x7S4fX5eUpuFQmOfOX5WulQWe5tU8sMNi7yE+4V6IWHilzWFmBZykOofxIFsSsHiEEuIOgQK4Tmw3gJXcOcNoWwbVZhZxQQk+9OXV6Lo/A0iYbKQePSwGkzlai8LHaz6XeH2yT5XmfCybTd7yWsoZIV7Ear2u32aq74O8yW5LNKoWYUSrBO7Z1E8/xJogEwM2usF0iDHg+te+Xx8k4p3C7hUJc2nYKeBnT5Pshol9fKvZOqdXKkUNc7U8augTpxbeNGN7MVf6We7oeA1scAgMTmhdYcpcrBomhCSjXknoOtwpblZ4GVe/n8t6Jk94CUkItwD+hREBqjZsbXyMbhGL+q669jTqz/dyDFjtRCRRN0CFXDA8soYPZRsi400hoNlhaFAPqibziVVNYgN0uckRsxYfi/B8vY++qlLnsHcnQRRZxStFYTsNynj9aCpbxXzfsF/ocAE/+Hv1rUYrwOVaStqlEFz1+PdQmNBhpKtHvUCbHHTHfmzE9UKArD8rdU3np0UP2uWYPh15qvcfir+wDk9IXQrefqeQJPW9KvbPYnvIVWIaBLPycBZxGNCa72UvMs1DbjBCBglE00zD+R5Df78HkKvJ6bHg=
    JWT_SECRET: AgABxVgeVqkAFV+ZkONT5fmh76Bay0CB0TEw43b5JogtSqd90yTKbflXEa/jiDY+QnX5tyUk4dBmeUAoVcBb2HM428MSJf/tuWy7O6wZ4BFFQ3CAVSInFRdikqIf11S65OY690bCwYEBZJesXxU9JrLhaGGD8tftXbZDYDU2ACY3LEiqYoHIVPOtcnvK+k/I8ArkA5K1YUTnw7HyK9xYH9m2MQb6/D3VGftHgU6/nZPZKNs6Fxy7R4bihIJ7uql7D/VURO0rkH4oXsGaQndhK44LKOqEY5OGMrJ6Q0/7mHU4+QWjoHubbidIc0T/L5POoBOuphXWyUPCTNuPcOY8WazM/eqFsL6B/GLyq8msTpDplaEtJTJBwnHucD9SAkvDPbY3Uqtz+BA6hvbISyClwNfigEQC/V/uKTezvlAy+MkZbV+xR1QSEgOQJiWf+fPRJzQiQJ5GbeCEZ6ZYjavuSW/bWmNkYm61wyKwzvYjgTYS6HCaFbnYVTZhW5Q6IDhe46xhGUx0nTG/a5sxilcjKqnyo5+MDlwjSaFkwGxxGhUnwj502E6ajbVDB0Vya2v9rlrQkzs0WZKW3dRaqpnU3en/hq62CoDZPdLzJI2yKILWDF5TKdURtQXn/Fjg6c63aefiBQHQG6WN3kCcgzRMJSBxRA1jkGpHPQxqd6caj5C8ds5UPOZk6WtDH0mu0XZOKUm4H5ixTK3e71Gg8WsvqGOE5JYxPxxUPfi34PLqYMFZehk9lvdi32m/hiO1zKg6
  template:
    metadata:
      creationTimestamp: null
      name: crop-advisory-service-secret
      namespace: dev
    type: Opaque


# apiVersion: v1
# kind: Secret
# metadata:
#   name: crop-advisory-service-secret
#   labels:
#     {{- include "crop-advisory-service.labels" . | nindent 4 }}
# type: Opaque
# stringData:
#   DATABASE_URL: "postgresql+asyncpg://{{ .Values.infrastructure.postgres.user }}:{{ .Values.infrastructure.postgres.password }}@postgres:{{ .Values.infrastructure.postgres.port }}/{{ .Values.infrastructure.postgres.databases.crop }}"
#   DATABASE_URL_SYNC: "postgresql://{{ .Values.infrastructure.postgres.user }}:{{ .Values.infrastructure.postgres.password }}@postgres:{{ .Values.infrastructure.postgres.port }}/{{ .Values.infrastructure.postgres.databases.crop }}"
#   JWT_SECRET: {{ .Values.shared.jwt.secret | quote }}
#   OPENWEATHER_API_KEY: {{ .Values.shared.openweather.apiKey | quote }}
