apiVersion: v1
kind: Secret
metadata:
  name: crop-advisory-service-secret
  labels:
    {{- include "crop-advisory-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.infrastructure.postgres.user }}:{{ .Values.infrastructure.postgres.password }}@postgres:{{ .Values.infrastructure.postgres.port }}/{{ .Values.infrastructure.postgres.databases.crop }}"
  DATABASE_URL_SYNC: "postgresql://{{ .Values.infrastructure.postgres.user }}:{{ .Values.infrastructure.postgres.password }}@postgres:{{ .Values.infrastructure.postgres.port }}/{{ .Values.infrastructure.postgres.databases.crop }}"
  JWT_SECRET: {{ .Values.shared.jwt.secret | quote }}
  OPENWEATHER_API_KEY: {{ .Values.shared.openweather.apiKey | quote }}
