{{- $svc := index .Values.services "crop-advisory-service" -}}
apiVersion: v1
kind: Service
metadata:
  name: crop-advisory-service
  labels:
    {{- include "crop-advisory-service.labels" . | nindent 4 }}
spec:
  type: {{ $svc.service.type | default .Values.global.service.type }}
  ports:
    - port: {{ $svc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crop-advisory-service.selectorLabels" . | nindent 4 }}
