apiVersion: v1
kind: Service
metadata:
  name: crop-advisory-service
  labels:
    {{- include "crop-advisory-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cropAdvisoryService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crop-advisory-service.selectorLabels" . | nindent 4 }}
