{{- if eq .Release.Namespace "dev" }}
# ─── DEV SealedSecret ─────────────────────────────────────
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBQI7n1sZs4Kbw1C3q5q8UxoSiaocnue/+jx/I1E5OHB1seMfGuVdWIEXVpZAUept+8CymetI+rAqxSZ/PXwz1AOqO+vCikj5+Ik18lR6XkJDyDla1nkQ/mn1MTLViKf4GBg97W3F6lnjLjKzPqNakNK52bm6l+WnTByeaPlx0bsl9dOgcAfjLuqMtHkFS8STgP8Fr9vIdN1EybamnU+I2TqaptbYPc48W49k5w4K2bM8I/rWET8cG2wvHw8y2AKh0JnXfXG+vAQmMc7UdNpeFrhgcoE/4l67+2rLUvWIrRW/o0qZ9ucb4gnKabycqbqc+PifuW09Sn9BwoacL1K2iEih6g6YvlyJ19WzlNHsV6BXei+XaETxxpwtl6jHF2mrgyofq9DL2kSDTKkiMf14R0M5S1kmBO7NUqEL/7zjy7aEnkBfR5uPedm8pOpAJnUXPDQGa+0DOjvdTHJMEVF1Lo5ekEXhBR0ramQLvriHovMLW4ng3ginIpeA4+bKiTNL3GJP9Oypp69wbAOulhN6pnAFsdnmrrxsYAag1+XL1dXGLXB9zPDdS++LA0x1p70b3isLblY1RYlaV6H40Ip7poM4hKVKjt7gVd/RgqLqW7xr+zpU7EJlJP7645w0JqHVs8TvOKDPFGxaVIYY3bQ8rHViBFAwnKqMAUbYw09bDS/ubffTGCl0irjxQvOyYpMCJR0/USYMu9F/oFF2QHMNTYFw==
    POSTGRES_USER: AgCrxeFbbq2JzVyjAYJrNOfFmzTU+526Bd/YWYUJqiDqokvL7BNZOXPJTgdUdVnDFlgCquFiuU+rlpgWussJqVod/dRDCSS9EjlNrqgSJIIhiEuEIyiA/l+Oq+M4ywnfKzeoUY/mFHUf50xasEHmVVRAYH13IrAGayyTno8HkDucR9FMaYqAsi6AWLFD5G1wg94PiyWkrin8kricT9sIQJZplUBgUONhdurbDADantHWa+xv61IrCZAbEvJ3wsz6U1sDsyZMx6mId/Lg/E4z1Dwax5+vvfCHNP2DRNhtc7Zl+N7t6eGWnTdLQzpdv0yfusD1nfeISHWTHTZTipbW/+D5jHQWvkrP9nqK6Uyi5cZUN+pNK1LMPXGdJeMIsPwivWozs2rnJHZOHJ/aqVzaEubORBTlP+OsKFF11CFhKw8z53YfhD7wGuWZV69kFFYD4XpyofK1BNx3/p/liKhpffFKwR4Iaujeo4M0fePoM1CSMeX1UY1dH1zXDq32Vjv0jfQgwyOsAreZODi5y7/XpvnTmyzLb9j5VmNlqh5boZge4R1dj2lkr4o9tvUR8iklWHueEqtTosGnfZ+hRadTTc6DdN1CX78x9cDyp+WaoEU+YCoaOIUVQOqR5+VLmy4r2RllqO1fk1XXcCxanO+p+OGVN2s/yF6bOCSx54lsHaKjX22t/xS9HGcOXnN8E0LbAztSpOHhoBUJ5A==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: dev
    type: Opaque
{{- else if eq .Release.Namespace "prod" }}
# ─── PROD SealedSecret ─────────────────────────────────────
# TODO: Run kubeseal with namespace=prod to generate encrypted data
# kubeseal --format=yaml < secrets-plain/postgres-secret-prod.yaml > this-file.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: prod
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAX0yqtlbzwuc1UXN7WGYALWUyyxJBY81keZeX7GMhyvAb2Gzz1e7/nuvGKVM8Rm1dbl1bbfgzMMYdLAUmMO3Fb9xxnU7jAN6phhN10IwbTkLfKS8qjVfvgGcQ/pfwNLa69MpIdJ50RyfqZUwU55eww6O9sBiEps8HK2F10VKB3y2PSVuc5UmmCrhONyClqhJFRg1XqR1N7MfNL9DYs4SjnnbUgp8nh79UEpcpSZTjlfXsOjPCJt1qnm3kCQqYMer2kp+dx0+i4aPy0+aBum42J13O5tw7vfSng+JpY63BbdpQemZoPfrZXdfsXnckiB1W3FyNkFqFyF8sGeNrgtYNW2iZSMUzkyAwgwS4u7hTLb5GB3kTsKlqhjANvFGHSE3bLOozyddoYo3krvJ0GhTSUn+7CSxTyoG/Gl5wQOiOG11MbLSB5E7UE0+ZygBMdqkvsK85MxNRxCN0KXINx/3p9pSEfdnmTCRLQ7v+qZnZbBq2d+P3Lfey7iKVMi8YBd90HEugjHYHDhiBDYrqnnD3bJXyFTVoErPAho5PbIjUHMlUKDhxieCBqBTFcEBY4UUuRuuQk4vJP8w0XCv9Edg5+jL4XZLJ1jAxsAF9fnH9sskT2ZyDbmgdZE3wA2tWf2JqUQlA08d+0zMJEbijuxErLG3woAAKIUwUIcEhMWkPclJzs4DdQapPY5NuOzdK+Qfq/JjEZcK3sx97lLf5NbjLMf2Y=
    POSTGRES_USER: AgDAID6UgkRV/hQFlm1si/SA5KVy6sxbWNbdPqC+ejXBZzHpFIlGtw/D61EPgBZ77DoREHDurHe9jQJOHIuR8wHbugI+Jsjt+sLPKHE8C4oyquA+U2Hxz7BTiFp898XFJEVcolzfNZtuQP3BY/vdor4SKD+VcOCHWR4U79w+lpSXHxOSCrJ0qVV1/Vn5BdWolMRAwKhUfzZv/lRKIQM8HRd5PN2NWqA0NnANGIHr/suhYCTIpy1ZSiaqQWKydeLgQoOg4b0jPtTbHN8x2OwUjb2QlTZ+8YwOHnVPvdz2FUxVOq8x6OEeGQnfXc1A3gWvIA6txjDCHKliTgr/mrksd6VoyP8D2w+dQXvG32ciqE2l8nvKHS0MlRXJsH/v+fWJTl5aDOMRLlZ5dEqCym32QV1X77Nmn/pe40jEve0tGBVf/aZw1g+y1zvVQWxfDL3uek6VIa9LwntywQwa+VhtH4MH3wKCFH8VJpJP3K56xm8KMhUlh1QvYybeenkqk3UyLIC/YH7Iqx06M5pQShzHOtpXM2iXIcgxIzGLz2LlXCGAw7+7YyMAWtOxtkUWIzZdvctxdY2Cjw249z7fgd733CbsgSCqQ0xgIivIRPErhi0z70ly/oUzWgMaSpaKt/NpWCirbuFIjxJRYOMmzLEcQfRQs/yCt7xWP1Sf3YMoxJfdnuwzKXuzz1+5/2DsMgkpxsurNZ+n0GYeWA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: prod
    type: Opaque
{{- end }}
