apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBQI7n1sZs4Kbw1C3q5q8UxoSiaocnue/+jx/I1E5OHB1seMfGuVdWIEXVpZAUept+8CymetI+rAqxSZ/PXwz1AOqO+vCikj5+Ik18lR6XkJDyDla1nkQ/mn1MTLViKf4GBg97W3F6lnjLjKzPqNakNK52bm6l+WnTByeaPlx0bsl9dOgcAfjLuqMtHkFS8STgP8Fr9vIdN1EybamnU+I2TqaptbYPc48W49k5w4K2bM8I/rWET8cG2wvHw8y2AKh0JnXfXG+vAQmMc7UdNpeFrhgcoE/4l67+2rLUvWIrRW/o0qZ9ucb4gnKabycqbqc+PifuW09Sn9BwoacL1K2iEih6g6YvlyJ19WzlNHsV6BXei+XaETxxpwtl6jHF2mrgyofq9DL2kSDTKkiMf14R0M5S1kmBO7NUqEL/7zjy7aEnkBfR5uPedm8pOpAJnUXPDQGa+0DOjvdTHJMEVF1Lo5ekEXhBR0ramQLvriHovMLW4ng3ginIpeA4+bKiTNL3GJP9Oypp69wbAOulhN6pnAFsdnmrrxsYAag1+XL1dXGLXB9zPDdS++LA0x1p70b3isLblY1RYlaV6H40Ip7poM4hKVKjt7gVd/RgqLqW7xr+zpU7EJlJP7645w0JqHVs8TvOKDPFGxaVIYY3bQ8rHViBFAwnKqMAUbYw09bDS/ubffTGCl0irjxQvOyYpMCJR0/USYMu9F/oFF2QHMNTYFw==
    POSTGRES_USER: AgCrxeFbbq2JzVyjAYJrNOfFmzTU+526Bd/YWYUJqiDqokvL7BNZOXPJTgdUdVnDFlgCquFiuU+rlpgWussJqVod/dRDCSS9EjlNrqgSJIIhiEuEIyiA/l+Oq+M4ywnfKzeoUY/mFHUf50xasEHmVVRAYH13IrAGayyTno8HkDucR9FMaYqAsi6AWLFD5G1wg94PiyWkrin8kricT9sIQJZplUBgUONhdurbDADantHWa+xv61IrCZAbEvJ3wsz6U1sDsyZMx6mId/Lg/E4z1Dwax5+vvfCHNP2DRNhtc7Zl+N7t6eGWnTdLQzpdv0yfusD1nfeISHWTHTZTipbW/+D5jHQWvkrP9nqK6Uyi5cZUN+pNK1LMPXGdJeMIsPwivWozs2rnJHZOHJ/aqVzaEubORBTlP+OsKFF11CFhKw8z53YfhD7wGuWZV69kFFYD4XpyofK1BNx3/p/liKhpffFKwR4Iaujeo4M0fePoM1CSMeX1UY1dH1zXDq32Vjv0jfQgwyOsAreZODi5y7/XpvnTmyzLb9j5VmNlqh5boZge4R1dj2lkr4o9tvUR8iklWHueEqtTosGnfZ+hRadTTc6DdN1CX78x9cDyp+WaoEU+YCoaOIUVQOqR5+VLmy4r2RllqO1fk1XXcCxanO+p+OGVN2s/yF6bOCSx54lsHaKjX22t/xS9HGcOXnN8E0LbAztSpOHhoBUJ5A==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: dev
    type: Opaque

# apiVersion: v1
# kind: Secret
# metadata:
#   name: postgres-secret
#   labels:
#     {{- include "postgres.labels" . | nindent 4 }}
# type: Opaque
# stringData:
#   POSTGRES_USER: {{ .Values.infrastructure.postgres.user | quote }}
#   POSTGRES_PASSWORD: {{ .Values.infrastructure.postgres.password | quote }}
