apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.infrastructure.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.infrastructure.postgres.password | quote }}
