apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.infrastructure.postgres.port }}
      targetPort: tcp-pg
      protocol: TCP
      name: tcp-pg
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
