apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-service-secret
  namespace: dev
spec:
  encryptedData:
    DATABASE_URL: AgAqceGNI3nL69KGmNsOkIKKDRu5NTIqVILbs5t4EZgIyvmOu6yOfOfKCuyhfUb/djT3OESkfdhLfru9v5B3IhNSVm9njltxz8I8GlaqXxX/+RR7OkdRUxrWACZ7Jfz4gM2C+LXHXDWKy1mZKZw0wLxEMO4bYkfQ1OrnfCST+1g3Tn80eEcQUXZfPlsxekN/1SGUmn7egh+nd/iHF/MBf7q9GIHnCZapoFVM2Q00BCu/tQVfPvmkXr1rjCYqg7Iput3FrgWG+O3rSJbDYaJCrf1LBv+qt+GiIySuMMdKAr7Z8EX3fVdbTQUuDmoKyZMiEN0/5wJ2PYQJEkKjvlNU3XDvitsuOugqEbVgkDImGVz2GXLe0EDaGWH+f48DspJBDMfTgEJI3zaIS7tyOlnrRBqSqtlrjYAFm94GQblDQ8clLhL6mJqCZM3nHudf4N/D/sXPCMSXUhAUos6Kko2vbj45mpJzdq+m7D1eUFHIlgxb+UMfvYDXOt5NRaY1y1hKqv1BRuQmBtjuqfyb6E2YgVcC1zHdqtx1TcfNU+s0kThh6lxT5ynWdpgYhv2CfLxyfqQ+Nuic8xrJnm6f9SBpLVtR2RQhwqPsETCGCl2tiutGrmYHXcrT4GTghzmup1dQonOb4s1pzig4tKvOmoIy9Jndtj5SR+XKx0lArOdNXClihGZGC8u9Xo+tye6XOBFYfweeNMjZ4mQM/mALZOFK1HO15VedwO9oxakg/ZZ1RBqJdjgdY+p/YUUYxfgl6GJA5J9PUiVON7vL+plvDqNhfYQm4GuEDQ==
    DATABASE_URL_SYNC: AgA/RMl9zMK4cmQga79nlfZIsQTGDk95WU1aQbi0MueHe2/dWTcFuAdpokKTa0eokDe5huOMMwuxp+jVCfPzkybhy0w8yhlAHpGtkrDxan3nQHPx6tLS4TftuIxmd8py5pLjpdUg3ZLzsaf6ToBDDYnK8N2GwJGuurJAxC/AzPcu4FjAeEdfYnO+N1msVkrrNqD04ChsAcPiORkoti2VVF6QJWBegNDCWynHGJxSxqQ9MIpnX2MHUpW35EBLzqFXwyFuC+YeBc24s+E3yd2E/BgpTL5c5EB0vdZ1GcDsxhKuBSs+Ox6SOc8C00465F6zqJji4b3tzSF0OwhOfsADfDaZFIUAfrP4+QywleS/4WWQr9c8eoKDr8HZIhfBQHEAy3yPrthu3Dvq6fdo/MmlWCobAPhk+ZJg/HLwoVOdQI5TpHSdr3ZL+J7znMu0W+tdL2BGwz4aYRBj9RW9uBnhuSIUAvT3SqSAPqhBJWk01jRMK/iodgp4wXyjj+hmpPzqYWnqO71CUzwGmXldc6FLtfdlqhM3gQMGMD7Z3hXZtJsxEUYwvvHmAs4CiiaAjfXuflNUO7QMj7FLCLDMkeIZEG8bKcunV7EEh3gRCBlRZwRzy6Kq1ZdGG9S0t589CooST4NeQld5hJgw06KD7iwyapntojx2Vr4KY+O57a5rXf6eN7J9XyTmDJYv7kBQpaxJW1d0RZYpwAIcdEBb5V6hg5LHOIbI/RVG4KA+5KIu6nlD7iaSx49Hrd1Qy+OR2GNyJXvm+QTfJgsY4Iaswy8=
    JWT_SECRET: AgCbuXoYz4IQY7405HUqQk5vStszIapQofnlx0kfzEETDFKgJv+RfZ0FRN4H6jpGYci4ElpNyGKBahGmTdd36iUiT6gr+RIAZpGJTH/LcCmyyt/w1jU0FIiyS9J2aYytHfAGLNtxhOao4MQrPBsi4ACDo5Kq+XGC10w4qB+1KM4ZG9hPHSo9Ug+P/9SPW1/UIJJBGqbBMpuOuE68J8BdMZPDUINgz1k20x3Rx6NgJeDWTdKgxWp6oBiMfYhYjhWndsuqlAjuouRvcVsVlHKTLxzUgKDjlXaZ8pC/EzLjALWuFmwE9m4JmW1d7r3BjhFFi0NaIk0UdmMk1WegxAD1CYxKZDFabX42cVW4UdCeRyQU9BTrWJiQULf4oGO+pNQeAdlgl1XE3veYLltBzicDnXH3Of7QDqedl0SEd7CLk4BS/hTeq2sX+T+v5n97irdkncwe/7tzodghpIs3KP3MrHjFeUvjBhxxv9hG4hbn3WsJjHlk3GO8avxInelCAEHi/37VF6V7/cZxofWcH3OBZOkG6rdyK65DBOcME3DeB6sSDHPX5hDpC0ZFrzgVpiIadyUjuRsVp1ZCaKdjjvBQoH3kEXyJ/r0ttyTh2zo2FX5B994FFQtHV7iJ7cxyePz9ic50RC2lu4mrl/055NhONNsCdZyfTnPGYUlo3TYWWBWA3+GGIU+vIloeBXecY1Lyv0DhLqPdo9EdrurUFonX7IWS8a2oKQ77YtZ0EK+KwZ/+mjDExx2cPE6JWHeaiVFX
  template:
    metadata:
      creationTimestamp: null
      name: user-service-secret
      namespace: dev
    type: Opaque

# apiVersion: v1
# kind: Secret
# metadata:
#   name: user-service-secret
#   labels:
#     {{- include "user-service.labels" . | nindent 4 }}
# type: Opaque
# stringData:
#   DATABASE_URL: "postgresql+asyncpg://{{ .Values.infrastructure.postgres.user }}:{{ .Values.infrastructure.postgres.password }}@postgres:{{ .Values.infrastructure.postgres.port }}/{{ .Values.infrastructure.postgres.databases.user }}"
#   DATABASE_URL_SYNC: "postgresql://{{ .Values.infrastructure.postgres.user }}:{{ .Values.infrastructure.postgres.password }}@postgres:{{ .Values.infrastructure.postgres.port }}/{{ .Values.infrastructure.postgres.databases.user }}"
#   JWT_SECRET: {{ .Values.shared.jwt.secret | quote }}
