{{- if eq .Release.Namespace "dev" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: marketplace-service-secret
  namespace: dev
spec:
  encryptedData:
    DATABASE_URL: AgChbyNcolalOSdsgi6mKhqDaBSHpWnsq2GYdwy8e5TDNLUdaogdovQnODdBxW5Ee/eQ9qCywy984h1KL8lcwwzvQHygzS6cw+BCCajNZ3lh8APFESEMCU0QZXt50DO1WnFTXBK5PZN9CLis9pPcdAFJCo7s5OYGLRTe6dY+6IEQA95wvIb8BOVxAu+tej5p8FgMw2PjfRXkC8SGEz3D5n851HSXhuHfXIfBiFM2CoOTAjRH7t+z6ZI8+pH5HzfqCC6y84ic+l+qTQblNrN0QzruHqEM0Hm9yn5G9uJT+RohTi8z/VZ99h8EXGR1bRY/Svmb71UxMmDGg0W9s7g1QRVUe3aoHWdFzL15oAr7rmQhYZea9q29kUw5McQolxEtvXROo3uwGNxAyklb6QXiUN2J5j3AlkrMy9pK5wpO6VpcXDM3EYrv2rTk9fCib/SQfTFXX7t56/S65RPGqUN3vTiP49oO7A6NBRXU4aCuokxATr5vTdFfMmVtMw5Ir3qVvk/pnTEqBZzxNzRffOIT1FTJCt9JCffx5AUS4k1w6ZLOTsA5sRBzQUUbEU51xzviHY2bSKMNNfds+3P7F1r4p4QjnHA3kqm6bYUej6t8z8May5LEn25hD7MuVDFdM6DMfh+2Wu+G9b0URcSi0P0wYXGv9yBhQkwE99kyuxZyo0IP0beY5SkCjE3eoD+uykk94mN67rM7u0aJpBFqPmdAkx/XUsNAu+Llx441kpT1NR9Femil45CDG6RGrtjBMJ+R7Wf55FeeMQMv/iicT4EYoW2LFkFYZpbY
  template:
    metadata:
      name: marketplace-service-secret
      namespace: dev
    type: Opaque
{{- else if eq .Release.Namespace "prod" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: marketplace-service-secret
  namespace: prod
spec:
  encryptedData:
    DATABASE_URL: AgCsOuKhdufV9ugIOw8g/WZBxlWgg0d6g7vyBmWxNYu6VWfYH5XgX/Y2rc3zK0hwlRgD63xXpnsGldApAAWsIEIN/NkokJ/U60iMhs0AiO23UoXBrItkFZHTfSEBMkgZseAgwDrZZetBljNa9TjZX6IUOVN8ELyCXcpeiRHm9rFlP1u3dBxmaK/JGrZxtNfVH7NkIHuAG6mIKPeNOvvDASRd7pPl8p+7pTZ8AixQaFrL7+azRru3BVZV8ymz2aW4QzIEjBun47x9SmnURkkGh1SOckF5e0X0y1Hob5ePGU5MbHJIehTVYV0m/BwjXITqhgyco15YjgMj7fW8Lt0uYU24p0MBaHI6oQnVngcqlIxlTQKC5dcdAGzyhDcYHFmSu5qyUHlmIU2PS/b6Hx6w2RRlRoKlUeKuKT6C9tidHtDvxRJbjpmfg8rnAP+6C43KroklTIbmVu1BEVQ0yISScqrdqQwXrGe0CPw6r6E+NSrnxhA4bQwj4RIC2vX8ndcjLE+fxL3KvivE9kfG2MFndu3rFKTLoNieIegsJEPrjBepwHJgpGdGe/kSYpphLA57hARIRk09kZ2sjOPZGAWwwBT7FFE8Jn9zkzTESWNQJu31+SMwT/Kl4l9IR8tmPNrZwj4NiOMY5qTkg8I86QYjknjWBE7Kedlt5v4CC9dh9oK+oSxBu+WHR8RQP0644KhNktlaq/Ilyr+THlyWGiRFCJGdU2q5rb48dkRY0k4YwILBZqiTnzmtBLX2daZSoa8si9i+7L8ObeVAaFAavapV2gIphgzn7vLJYA==
    DATABASE_URL_SYNC: AgB9LjhZdkaaV2tnuNgl7K4+DKjhgppVHvm5lVnWP2Gu+efsfcwNfA7gwWhsI9H0tK2uZUhKA74dvaXbYi5om0sxbNVwYSEt1XsfLZc5TUFmcHTPAHH6rmlRsGvI6UG+1cU2NktEzK20AXbefR/Uxle1xniliGZkbBdSGQSZJRgCWx/P/GyP5AILg1hvv7ZhczC5koE1c6BXSCUyvmLgWXVOdiBhXMLJ62/uvZu4Yb9wDkmeRdorYi/TrjTMuKpEFn19YpIWWqSQlgS4pQPSbWrIbnPY4ubIeA7SNtxH5Y5WqJ+Ss+ZB6JqouHbxmVoa7l1Nd//zYU/a1g5rwmevRLZ52izisF/Ve8tLbAAPJyAwFwFkurrJbQrElC/QAeOB65ffdY443kj7WUq1+DYZYcRNXQNcBboDt90gKNijiE2tmlYQx2bMcP8g73zD087Rvib85XNTwNLMLPZ3X75RmfzQZP6YyvyAELSFgPgYSTIb/McoKygHfJyrGwX4wfp2FCQGalUb9DDC6iBwLUorn6orUGOn4OPFvIyfT9sUT18XOEju5pS1+Ppduefwn35gYnojVKM2ObXzwa8QDLpWSRPJBHs4EVE/mYfNDjuNv40JubCm1vhqJKQDUm+VcPVnVaLTN19snmrpZEZvINCJflpKr+5TbwMcPpC0AfQvLFee6b+tYbl7vwKk4i6vUbU+2Cmlw68wlaLS84xMwsu607U7pxaFyo8OgEb2aamQ6fP6veoc+MUuu+kvO2/C2w2ZFC72vU0KB7dg/wNBEXMGX74=
    JWT_SECRET: AgBQVe8m+DxbHlphXuf0Ufm3IvCXQzX6W9M8/8DASYUNCPchRwrvG2VEJ48uK+f3iRKqtvSTaRKQRySksVGVuCwWtwLWACpLcmj/xjD5t/HfR0C45xafpIxG1mjz8qcMAUgE8L2ni/GBME/hj0mzBEdpYg3SzoupsEOx9mw3BFgnOdKmMrhbf6CU0C/I6mOJqScYkxHa6/LkMq4byupo4gjs6m0PKE9QPfnVhnyNrhzuK4xi+cYW75mVi7TifZjq8ekURcd8NuX7jSglhYyBmwDLoVOigWEO+/rhOoBvpAGg+TDzbYon7c7W9SpC1jcJGMoYJstiVBFoN1dqmED2jZDblMz53uQdyNE8KNbjPK4/mThKlneig7OyIueOHq0G09/hsOzcc9l7QRVaNFm3ku62RX2MZM8bZeQQzQuVZh4zeeDRhG5IC7EXPKKCNomIzIjXl2QGWnvEBy85YoS733mO/kUYI4Udl0eWEUeMf8TLfW01MuIzQb1ka28tw6bkZ1IOzEThiS+tg/NUAOs5FcBmN0ggjTdAXgAXtba30cPwKduuaiJIdt8weDYok1dzf4/yeNTOpQJfT7SlwVZ8h+HoGx/o3HREWlkUEh9RZNdL1blj6Ao/LHiFY2PEdUTwQNi6hh2tnmDTb4f3OWSZKL18+i4l5QKxpAnvdSSVfNuve5YSFUyifnil5zS0tXi+k2M2Zn9LRLpzuJm3QhLcZlnUoEQ+IQ==
  template:
    metadata:
      name: marketplace-service-secret
      namespace: prod
    type: Opaque
{{- end }}
